version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 825312798806.dkr.ecr.ap-south-1.amazonaws.com/library
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 825312798806.dkr.ecr.ap-south-1.amazonaws.com/library:latest .
      - docker push 825312798806.dkr.ecr.ap-south-1.amazonaws.com/library:latest
